apiVersion: apps/v1
kind: Deployment
metadata:
  name: sid-cloud-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      labels:
        app: cloud
    spec:
      containers:
        - name: cloud
          image: pruthvi1902/sid-cloud-service:latest
          ports:
            - containerPort: 8092
---
apiVersion: v1
kind: Service
metadata:
  name: sid-service
spec:
  selector:
    app: cloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8092
  type: NodePort
